// AUTO-GENERATED 英文词汇 → 中文释义（由 3 份翻译合并，勿手改）
export const ENGLISH_DICT: Record<string, string> = {
  'about': '关于；大约',
  'active': '活跃的',
  'afraid': '害怕的',
  'afternoon': '下午',
  'ago': '以前',
  'angry': '生气的',
  'animal': '动物',
  'ant': '蚂蚁',
  'anything': '任何事物',
  'apple': '苹果',
  'apples': '苹果（复数）',
  'april': '四月',
  'are': '是（be 的复数形式）',
  'arm': '手臂',
  'arrive': '到达',
  'art': '美术；艺术',
  'art room': '美术教室',
  'art show': '美术展',
  'ask': '问；询问',
  'at': '在（某处或某时）',
  'ate': '吃（eat 的过去式）',
  'attention': '注意；注意力',
  'aunt': '姑妈；姨妈；阿姨',
  'australia': '澳大利亚',
  'autumn': '秋天；秋季',
  'baby': '婴儿；宝贝',
  'badminton': '羽毛球',
  'bag': '包；书包',
  'ball': '球',
  'banana': '香蕉',
  'basketball': '篮球',
  'bathroom': '浴室；卫生间',
  'be': '是；成为',
  'bear': '熊',
  'beautiful': '美丽的；漂亮的',
  'because': '因为',
  'bed': '床',
  'bedroom': '卧室',
  'bee': '蜜蜂',
  'beef': '牛肉',
  'before': '在……之前',
  'best': '最好的',
  'big': '大的',
  'bigger': '更大的',
  'bike': '自行车',
  'bird': '鸟',
  'birds': '鸟（复数）',
  'birthday': '生日',
  'black': '黑色的',
  'blackboard': '黑板',
  'blue': '蓝色的',
  'board': '木板；板',
  'boat': '小船',
  'body': '身体',
  'book': '书',
  'books': '书（复数）',
  'bookstore': '书店',
  'boring': '无聊的；乏味的',
  'bottle': '瓶子',
  'bought': '买（buy 的过去式）',
  'bowl': '碗',
  'box': '盒子',
  'boy': '男孩',
  'bread': '面包',
  'breakfast': '早餐',
  'breath': '呼吸',
  'bridge': '桥',
  'brother': '兄弟；哥哥；弟弟',
  'brown': '棕色的',
  'building': '建筑物；大楼',
  'buildings': '建筑物（复数）',
  'bus': '公共汽车',
  'businessman': '商人；男商人',
  'busy': '忙碌的',
  'bye': '再见',
  'cake': '蛋糕',
  'calendar': '日历',
  'camping': '野营；露营',
  'can': '能；会',
  'canada': '加拿大',
  'candle': '蜡烛',
  'candy': '糖果',
  'cap': '帽子（鸭舌帽）',
  'car': '小汽车',
  'card': '卡片',
  'careful': '小心的；仔细的',
  'carrot': '胡萝卜',
  'carrots': '胡萝卜（复数）',
  'cartoon': '卡通；动画片',
  'cartoons': '卡通；动画片（复数）',
  'cat': '猫',
  'chair': '椅子',
  'change': '改变；变化',
  'chases': '追赶（chase 的第三人称单数）',
  'cheap': '便宜的',
  'chicken': '鸡肉；鸡',
  'china': '中国',
  'chinese': '中国的；汉语',
  'chopsticks': '筷子',
  'cinema': '电影院',
  'class': '班级；课',
  'classroom': '教室',
  'clean': '干净的；打扫',
  'cleaned': '打扫（clean 的过去式）',
  'clever': '聪明的',
  'climb': '爬；攀登',
  'climbing': '爬；攀登（现在分词）',
  'clock': '钟；时钟',
  'clothes': '衣服',
  'cloudy': '多云的；阴天的',
  'coach': '教练',
  'coat': '外套',
  'coke': '可乐',
  'cold': '寒冷的；感冒',
  'color': '颜色（美式拼写）',
  'colour': '颜色（英式拼写）',
  'come': '来',
  'comic': '漫画',
  'computer': '电脑；计算机',
  'computer room': '电脑教室；计算机房',
  'cook': '烹饪；厨师',
  'cooking': '烹饪（现在分词）',
  'cool': '凉爽的；酷的',
  'corn': '玉米',
  'couldn': '不能（could not 的缩写）',
  'count': '数；计数',
  'countryside': '乡村；农村',
  'court': '球场',
  'cow': '奶牛；母牛',
  'cows': '奶牛（复数）',
  'crayon': '蜡笔',
  'cream': '奶油',
  'cross': '穿过；横过',
  'crossing': '十字路口',
  'cute': '可爱的',
  'cycling': '骑自行车',
  'dad': '爸爸',
  'dance': '跳舞',
  'dancing': '跳舞（现在分词）',
  'date': '日期',
  'dear': '亲爱的',
  'delicious': '美味的',
  'desk': '书桌；课桌',
  'diary': '日记',
  'dictionary': '词典；字典',
  'different': '不同的',
  'dining': '吃饭（dining room 就餐）',
  'dinner': '晚餐；正餐',
  'dinosaur': '恐龙',
  'do': '做；干',
  'doctor': '医生',
  'dog': '狗',
  'doing': '做（do 的现在分词）',
  'donkey': '驴',
  'donkeys': '驴（复数）',
  'door': '门',
  'down': '向下',
  'drank': '喝（drink 的过去式）',
  'draw': '画',
  'drawing': '画画（现在分词）',
  'dress': '连衣裙；穿衣',
  'drink': '喝；饮料',
  'drinking': '喝（现在分词）',
  'drive': '驾驶；开车',
  'driver': '司机',
  'duck': '鸭子',
  'ear': '耳朵',
  'ears': '耳朵（复数）',
  'easter': '复活节',
  'eat': '吃',
  'eat breakfast': '吃早餐',
  'eat dinner': '吃晚餐',
  'eating': '吃（现在分词）',
  'egg': '鸡蛋',
  'eighteen': '十八',
  'elbow': '肘部',
  'elephant': '大象',
  'eleven': '十一',
  'else': '其他的；别的',
  'email': '电子邮件',
  'english': '英语；英国的',
  'english class': '英语课',
  'eraser': '橡皮',
  'evening': '晚上；傍晚',
  'excuse': '原谅；借口',
  'exercise': '锻炼；练习',
  'exercises': '锻炼；练习（复数）',
  'expensive': '昂贵的',
  'eye': '眼睛',
  'eyes': '眼睛（复数）',
  'face': '脸',
  'factory': '工厂',
  'family': '家庭；家人',
  'fan': '风扇；迷',
  'far': '远的',
  'farm': '农场',
  'farmer': '农民',
  'fat': '胖的',
  'father': '父亲；爸爸',
  'favourite': '最喜欢的',
  'february': '二月',
  'feet': '脚（foot 的复数）',
  'festival': '节日',
  'fifteen': '十五',
  'fifth': '第五',
  'film': '电影',
  'find': '找到；发现',
  'fine': '好的；晴朗的',
  'first': '第一',
  'first floor': '一楼',
  'fish': '鱼',
  'fisherman': '渔民',
  'five': '五',
  'floor': '地板；楼层',
  'flower': '花',
  'flowers': '花（复数）',
  'fly': '飞；苍蝇',
  'food': '食物',
  'foot': '脚',
  'football': '足球',
  'forest': '森林',
  'fork': '叉子',
  'four': '四',
  'fourteen': '十四',
  'fourth': '第四',
  'fresh': '新鲜的',
  'friday': '星期五',
  'fridge': '冰箱',
  'friend': '朋友',
  'friendly': '友好的',
  'friends': '朋友（复数）',
  'from': '从；来自',
  'fruit': '水果',
  'fun': '乐趣；有趣的',
  'funny': '有趣的；滑稽的',
  'game': '游戏；比赛',
  'get': '得到；获得',
  'get up': '起床',
  'gift': '礼物',
  'gifts': '礼物',
  'giraffe': '长颈鹿',
  'girl': '女孩',
  'glasses': '眼镜',
  'glove': '手套',
  'go': '去',
  'go home': '回家',
  'go to bed': '上床睡觉',
  'go to school': '去上学',
  'going': '去（go 的现在分词）',
  'good': '好的',
  'goodbye': '再见',
  'grandfather': '祖父；外祖父',
  'grandma': '奶奶；外婆',
  'grandmother': '祖母；外祖母',
  'grandpa': '爷爷；外公',
  'grandparents': '祖父母',
  'grape': '葡萄',
  'grapes': '葡萄（复数）',
  'grass': '草',
  'great': '很好的；伟大的',
  'great wall': '长城',
  'green': '绿色的',
  'green beans': '青豆；绿豆',
  'gym': '体育馆',
  'had': '有（have 的过去式）',
  'hair': '头发',
  'hall': '大厅',
  'hamburger': '汉堡包',
  'hand': '手',
  'happy': '快乐的',
  'hard-working': '努力工作的',
  'hat': '帽子',
  'have': '有；吃',
  'he': '他',
  'head': '头',
  'healthy': '健康的',
  'heavier': '更重的',
  'heavy': '重的',
  'hello': '你好',
  'help': '帮助',
  'helpful': '乐于助人的',
  'hen': '母鸡',
  'hens': '母鸡（复数）',
  'here': '这里',
  'hers': '她的（名词性物主代词）',
  'hi': '嗨；你好',
  'hiking': '远足',
  'hill': '小山',
  'his': '他的',
  'hobbies': '爱好（复数）',
  'holiday': '假日；假期',
  'home': '家',
  'homework': '家庭作业',
  'horse': '马',
  'horses': '马（复数）',
  'hospital': '医院',
  'hot': '热的',
  'house': '房子',
  'how': '怎样；如何',
  'how much': '多少钱',
  'hungry': '饥饿的',
  'hurry up': '赶快',
  'hurt': '受伤；疼痛',
  'i': '我',
  'ice': '冰',
  'ice-skate': '滑冰',
  'idea': '主意；想法',
  'ill': '生病的',
  'in': '在……里面',
  'interesting': '有趣的',
  'is': '是',
  'it': '它',
  'jacket': '夹克衫',
  'january': '一月',
  'job': '工作',
  'jones': '琼斯（姓氏）',
  'juice': '果汁',
  'jumping': '跳（jump 的现在分词）',
  'june': '六月',
  'keep': '保持',
  'key': '钥匙',
  'keys': '钥匙（复数）',
  'kilogram': '千克；公斤',
  'kind': '和蔼的；友好的',
  'kitchen': '厨房',
  'kite': '风筝',
  'knife': '刀',
  'know': '知道',
  'kung fu': '功夫',
  'lake': '湖',
  'lakes': '湖（复数）',
  'left': '左边',
  'leg': '腿',
  'lesson': '课',
  'library': '图书馆',
  'light': '灯；光',
  'lighter': '更轻的',
  'like': '喜欢',
  'likes': '喜欢（第三人称单数）',
  'lion': '狮子',
  'listening': '听（listen 的现在分词）',
  'little': '小的；少的',
  'live': '居住',
  'living': '居住；生活（live 的现在分词）',
  'long': '长的',
  'longer': '更长的',
  'look': '看',
  'lost': '丢失的；迷路的',
  'lots': '许多',
  'love': '爱；喜欢',
  'lunch': '午餐',
  'make': '制作',
  'man': '男人',
  'many': '许多',
  'map': '地图',
  'march': '三月',
  'math': '数学',
  'maths': '数学',
  'may': '可以；五月',
  'me': '我（宾格）',
  'meet': '遇见；见面',
  'metre': '米',
  'mice': '老鼠（复数）',
  'milk': '牛奶',
  'mine': '我的（名词性物主代词）',
  'miss': '想念；错过；小姐',
  'model': '模型',
  'mom': '妈妈',
  'monday': '星期一',
  'mondays': '星期一（复数）',
  'monkey': '猴子',
  'morning': '早晨；上午',
  'morning exercises': '早操',
  'mother': '母亲',
  'mountain': '山',
  'mountains': '山（复数）',
  'mouse': '老鼠；鼠标',
  'mouth': '嘴',
  'mud': '泥',
  'mule': '骡子',
  'mum': '妈妈',
  'museum': '博物馆',
  'music': '音乐',
  'music class': '音乐课',
  'music room': '音乐教室',
  'must': '必须',
  'my': '我的',
  'name': '名字',
  'nature': '自然',
  'near': '在……附近',
  'new': '新的',
  'next': '下一个的',
  'nice': '好的；漂亮的',
  'nine': '九',
  'nineteen': '十九',
  'no': '不；没有',
  'noodles': '面条',
  'nose': '鼻子',
  'note': '便条；笔记',
  'notebook': '笔记本',
  'now': '现在',
  'nurse': '护士',
  'o': '哦；字母 O',
  'october': '十月',
  'office': '办公室',
  'officer': '军官；警官',
  'often': '经常',
  'old': '老的；旧的',
  'older': '更老的；更大的',
  'on': '在……上面',
  'one': '一',
  'onion': '洋葱',
  'open': '打开',
  'orange': '橙子；橙色的',
  'ours': '我们的（名词性物主代词）',
  'outside': '在外面',
  'paint': '绘画；油漆',
  'pal': '朋友；伙伴',
  'panda': '熊猫',
  'pandas': '熊猫（复数）',
  'pants': '裤子',
  'parents': '父母',
  'park': '公园',
  'party': '聚会',
  'pay': '付钱',
  'pe class': '体育课',
  'pear': '梨',
  'pen': '钢笔',
  'pencil': '铅笔',
  'people': '人们',
  'phone': '电话',
  'photo': '照片',
  'photos': '照片（复数）',
  'piano': '钢琴',
  'pick': '摘；挑选',
  'picnic': '野餐',
  'picture': '图画；照片',
  'pictures': '图画（复数）',
  'pig': '猪',
  'pilot': '飞行员',
  'ping-pong': '乒乓球',
  'pink': '粉红色的',
  'pipa': '琵琶',
  'plane': '飞机',
  'plant': '植物；种植',
  'plants': '植物（复数）',
  'plate': '盘子',
  'play': '玩；打（球）',
  'player': '运动员；选手',
  'playground': '操场',
  'playing': '玩（play 的现在分词）',
  'please': '请',
  'police': '警察',
  'polite': '有礼貌的',
  'post': '邮寄；邮件',
  'postcard': '明信片',
  'postman': '邮递员',
  'potato': '土豆',
  'potatoes': '土豆（复数）',
  'pretty': '漂亮的',
  'pull': '拉',
  'pupil': '小学生；学生',
  'puppet': '木偶',
  'puppy': '小狗',
  'purple': '紫色的',
  'puzzles': '拼图（复数）',
  'queen': '女王',
  'quiet': '安静的',
  'quietly': '安静地',
  'rain': '雨；下雨',
  'rainbow': '彩虹',
  'rainy': '下雨的',
  'read': '读；阅读',
  'reading': '阅读（read 的现在分词）',
  'red': '红色的',
  'restaurant': '餐馆',
  'rice': '米饭；大米',
  'right': '右边；正确的',
  'ring': '戒指；铃响',
  'river': '河；江',
  'road': '路；道路',
  'robot': '机器人',
  'rode': '骑（ride 的过去式）',
  'room': '房间',
  'rose': '玫瑰花',
  'ruler': '尺子',
  'run': '跑；跑步',
  'running': '跑步（run 的现在分词）',
  'sad': '伤心的；难过的',
  'safety': '安全',
  'salad': '沙拉；色拉',
  'sandwich': '三明治',
  'saturday': '星期六',
  'saw': '看见（see 的过去式）',
  'say': '说；讲',
  'scarf': '围巾',
  'school': '学校',
  'school trip': '学校旅行；郊游',
  'schoolbag': '书包',
  'science': '科学',
  'scientist': '科学家',
  'sea': '大海；海洋',
  'season': '季节',
  'seat': '座位',
  'second': '第二；秒',
  'second floor': '二楼',
  'see': '看见；看到',
  'seven': '七',
  'seventeen': '十七',
  'she': '她',
  'sheep': '绵羊',
  'ship': '轮船',
  'shirt': '衬衫',
  'shoes': '鞋子',
  'shop': '商店；购物',
  'shopping': '购物',
  'short': '短的；矮的',
  'shorter': '更短的；更矮的',
  'shorts': '短裤',
  'should': '应该',
  'show': '展示；演出',
  'shy': '害羞的',
  'sing': '唱；唱歌',
  'singing': '唱歌（sing 的现在分词）',
  'sister': '姐妹',
  'six': '六',
  'sixteen': '十六',
  'sixth': '第六',
  'size': '尺寸；大小',
  'skirt': '短裙',
  'sleeping': '睡觉（sleep 的现在分词）',
  'slept': '睡觉（sleep 的过去式）',
  'slow': '慢的',
  'small': '小的',
  'smaller': '更小的',
  'snow': '雪；下雪',
  'snowman': '雪人',
  'snowy': '下雪的',
  'socks': '袜子',
  'sofa': '沙发',
  'some': '一些；某些',
  'sometimes': '有时',
  'song': '歌曲',
  'songs': '歌曲（song 的复数）',
  'soon': '不久；很快',
  'sorry': '对不起；抱歉的',
  'soup': '汤',
  'sour': '酸的',
  'speak': '说；说话',
  'special': '特别的',
  'spoon': '勺子',
  'sports': '运动',
  'sports meet': '运动会',
  'spring': '春天；春季',
  'stayed': '停留（stay 的过去式）',
  'stop': '停止；车站',
  'stories': '故事（story 的复数）',
  'storybook': '故事书',
  'straight': '直的；笔直地',
  'strawberry': '草莓',
  'street': '街道',
  'strict': '严格的',
  'strong': '强壮的',
  'stronger': '更强壮的',
  'student': '学生',
  'students': '学生（student 的复数）',
  'study': '学习；书房',
  'subway': '地铁',
  'summer': '夏天；夏季',
  'sunday': '星期日',
  'sunglasses': '太阳镜',
  'sunny': '晴朗的；阳光充足的',
  'supermarket': '超市',
  'sure': '确信的；当然',
  'surprise': '惊喜；惊讶',
  'sweater': '毛衣',
  'sweet': '甜的；糖果',
  'swim': '游泳',
  'swimming': '游泳（swim 的现在分词）',
  'sydney': '悉尼',
  'table': '桌子',
  'tail': '尾巴',
  'take': '拿；带；乘坐',
  'talent': '才能；天赋',
  'talk': '谈话；说话',
  'tall': '高的',
  'taller': '更高的',
  'tallest': '最高的',
  'taste': '品尝；味道',
  'taxi': '出租车',
  'tea': '茶',
  'teacher': '老师；教师',
  'teachers': '老师（teacher 的复数）',
  'ten': '十',
  'test': '测试；考试',
  'than': '比',
  'thank': '感谢',
  'thanks': '谢谢',
  'that': '那个',
  'theirs': '他们的',
  'them': '他们；她们；它们（宾格）',
  'there': '那里',
  'thin': '瘦的；薄的',
  'think': '想；认为',
  'thinner': '更瘦的',
  'third': '第三',
  'thirteen': '十三',
  'thirtieth': '第三十',
  'this': '这个',
  'three': '三',
  'thursday': '星期四',
  'tiger': '老虎',
  'time': '时间',
  'today': '今天',
  'tomato': '西红柿；番茄',
  'tomatoes': '西红柿（tomato 的复数）',
  'tomorrow': '明天',
  'tonne': '吨',
  'too': '也；太',
  'took': '拿；带（take 的过去式）',
  'toy': '玩具',
  'traffic': '交通',
  'train': '火车',
  'tree': '树',
  'trees': '树（tree 的复数）',
  'trip': '旅行',
  'try on': '试穿',
  'tube': '管子；地铁',
  'tuesday': '星期二',
  'tuesdays': '每星期二',
  'turn': '转弯；轮流',
  'turns': '轮流（turn 的第三人称单数）',
  'tv': '电视',
  'twelfth': '第十二',
  'twelve': '十二',
  'twentieth': '第二十',
  'twenty': '二十',
  'twenty-first': '第二十一',
  'two': '二',
  'uk': '英国',
  'umbrella': '雨伞',
  'uncle': '叔叔；舅舅',
  'under': '在……下面',
  'up': '向上',
  'usa': '美国',
  'use': '使用；用',
  'usually': '通常',
  'vacation': '假期',
  'van': '货车；面包车',
  'vegetable': '蔬菜',
  'very': '非常；很',
  'vet': '兽医',
  'village': '村庄',
  'visit': '参观；拜访',
  'visited': '参观（visit 的过去式）',
  'wait': '等待',
  'wake up': '醒来；叫醒',
  'walk': '走；步行',
  'wall': '墙',
  'want': '想要',
  'warm': '温暖的',
  'was': '是（am/is 的过去式）',
  'wash': '洗',
  'washed': '洗（wash 的过去式）',
  'watch': '观看；手表',
  'watched': '观看（watch 的过去式）',
  'watching': '观看（watch 的现在分词）',
  'water': '水；浇水',
  'watermelon': '西瓜',
  'way': '路；方式',
  'we': '我们',
  'wear': '穿；戴',
  'weather': '天气',
  'weather report': '天气预报',
  'wednesday': '星期三',
  'weekend': '周末',
  'welcome': '欢迎',
  'well': '好地；健康的',
  'went': '去（go 的过去式）',
  'were': '是（are 的过去式）',
  'what': '什么',
  'when': '什么时候',
  'where': '哪里',
  'white': '白色的',
  'who': '谁',
  'whose': '谁的',
  'why': '为什么',
  'wind': '风',
  'window': '窗户',
  'windy': '有风的',
  'winter': '冬天；冬季',
  'woman': '女人',
  'wonderful': '精彩的；极好的',
  'word': '单词；词',
  'work': '工作',
  'worker': '工人',
  'working': '工作（work 的现在分词）',
  'world': '世界',
  'worried': '担心的；焦虑的',
  'would': '将；愿意',
  'wow': '哇',
  'writing': '写（write 的现在分词）',
  'wrong': '错误的',
  'year': '年',
  'yellow': '黄色的',
  'yes': '是；是的',
  'you': '你；你们',
  'young': '年轻的',
  'younger': '更年轻的',
  'your': '你的；你们的',
  'yours': '你的；你们的（名词性物主代词）',
  'yuan': '元（人民币单位）',
  'yummy': '好吃的；美味的',
  'zip': '拉链',
  'zoo': '动物园',
  'zoom': '快速移动；猛增',
};
