/* 构建期脚本：用 segmentit 给每篇课文分词，生成 src/content/textWords.ts
   运行（项目根目录）：
   npx esbuild scripts/gen-text-words.ts --bundle --platform=node --format=esm --outfile=scripts/_gen.mjs
   node scripts/_gen.mjs
*/
import * as fs from 'node:fs';
import * as path from 'node:path';
import { Segment, useDefault } from 'segmentit';
import { LESSON_CONTENTS } from '../src/content/lessonContents';

const segmentit = useDefault(new Segment());
const HAN = /^[\u4e00-\u9fff]+$/;

const out: Record<string, string[]> = {};
for (const [id, c] of Object.entries(LESSON_CONTENTS)) {
  if (!c?.text) continue;
  const words = segmentit
    .doSegment(c.text)
    .map((t: { w: string }) => t.w)
    .filter((w: string) => w.length >= 2 && HAN.test(w));
  out[id] = [...new Set(words)];
}

const file =
  '// AUTO-GENERATED by scripts/gen-text-words.ts —— 构建期分词结果，请勿手改\n' +
  '// 重新生成：npx esbuild scripts/gen-text-words.ts --bundle --platform=node --format=esm --outfile=scripts/_gen.mjs && node scripts/_gen.mjs\n' +
  'export const TEXT_WORDS: Record<string, string[]> = ' +
  JSON.stringify(out) +
  ';\n';

const target = path.resolve('src', 'content', 'textWords.ts');
fs.writeFileSync(target, file, 'utf-8');
console.log(`generated ${Object.keys(out).length} lessons -> ${target}`);
